import Link from 'next/link'; import {CONTRACT,explorer} from '@/lib/constants'
const sections=[
 ['creating','Creating a POAP',<><p>Connect a wallet on Base Sepolia, open <Link href="/create">Create</Link>, add a required name and raw SVG, then choose distribution settings. Description, location, event date, URL, and allowlist are optional. The name is limited to 128 bytes; description to 512; location and URL to 128 each.</p><p>Registration calls <code>registerEvent(name, description, eventDate, location, allowlistRoot, svg, externalUrl, flags)</code>. The flags encode transferable/soulbound and public/private. Registration is immutable.</p></>],
 ['metadata','Metadata & SVG',<><p>The contract Base64-encodes the raw SVG and stores it with SSTORE2. Its ERC-1155 <code>uri(id)</code> returns an onchain Base64 JSON document containing the artwork, description, date, location, creator, event ID, CAIP-2 ID, and soulbound status.</p><p>Use a square <code>viewBox</code>, avoid remote fonts/images/scripts, convert text to paths when exact typography matters, and optimize with <a href="https://jakearchibald.github.io/svgomg/">SVGOMG</a>. Smaller SVGs cost less gas.</p></>],
 ['soulbound','Soulbound vs transferable',<><p>Soulbound POAPs cannot move between wallets after minting, making them strong attendance credentials. Transferable POAPs can be gifted or traded. This choice cannot be changed later.</p></>],
 ['distribution','Distribution methods',<><h3>Public mint</h3><p>When open, any wallet can call <code>mint</code>. Creators can open or close it during the first 30 days; public minting itself has no automatic expiry.</p><h3>Allowlist mint</h3><p>A Merkle tree compresses a wallet list into one root. The creator can set a non-zero root once during the first 30 days. Each attendee receives only their JSON proof and calls <code>allowlistMint</code>. The builder uses <code>keccak256(abi.encodePacked(address))</code> leaves and sorted pairs, matching OpenZeppelin verification.</p><h3>Signed pass</h3><p>The creator personally signs the packed hash of <code>(eventId, chainId, recipient)</code>. The contract applies Ethereum’s signed-message prefix and recovers the creator. Each pass is valid for one wallet and expires 37 days after registration.</p><h3>Creator drop</h3><p>During the first 30 days, creators may mint directly to batches of at most 101 recipients. Already-claimed wallets are skipped.</p></>],
 ['qr','Live-event QR workflow',<><p>Collect an attendee wallet, generate its signed pass in Creator Studio, and show or send the resulting QR. The QR opens the mint page with that pass. Generate one per recipient: the contract binds every signature to a single wallet, so one universal QR signature cannot work for a crowd.</p><p>For a single poster anyone can scan, use public minting and link the event page. For a pre-registered crowd, use allowlist proofs.</p></>],
 ['permissions','Permissions & deadlines',<><ul><li>One claim per event per wallet across every mint route.</li><li>Creator: set allowlist once, toggle public status, and creator-mint during days 0–30.</li><li>Signed mint: available through day 37.</li><li>Public and allowlist mint: no contract expiry.</li><li>Soulbound and all metadata: immutable.</li></ul><p>The contract boundary uses <code>createdAt + window &lt; block.timestamp</code>, so actions are allowed exactly at the deadline timestamp.</p></>],
 ['verify','Verify a mint',<><p>After confirmation, open the transaction on BaseScan or the token on OpenSea. The Gallery checks <code>balanceOf(wallet, eventId)</code> directly. You can independently inspect <a href={explorer(`address/${CONTRACT}#code`)}>the verified contract</a>, call <code>uri(id)</code>, and decode the Base64 JSON.</p></>]
]
export default function Docs(){return <section className="page docs"><div className="docs-title"><span className="eyebrow">DOCUMENTATION</span><h1>From moment<br/>to <em>memory.</em></h1><p>Everything an organizer or developer needs to use the protocol safely.</p></div><aside>{sections.map(([id,title])=><a key={id as string} href={`#${id}`}>{title}</a>)}</aside><div className="doc-body">{sections.map(([id,title,body],i)=><article id={id as string} key={id as string}><span>{String(i+1).padStart(2,'0')}</span><h2>{title}</h2>{body}</article>)}</div></section>}
